In [1]:
## Load Libraries
import pandas as pd
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
%matplotlib inline

---

Dot product between two vectors is simply a pairwise-multiplication followed by a summation: for example, $a\cdot b = a_1\times b_2+a_2\times b_2+\cdots+a_n\times b_n.$

---

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

---

$L_2$ norm or the geometric length of a vector denoted as $\lVert a\rVert$ tells us how long a vector is. In 2-dimensions, $\lVert a\rVert_2 = \sqrt{a_1^2+a_2^2}$ and in $n$-dimensions, $\lVert a\rVert_2 = \sqrt{a_1^2+a_2^2+\cdots+a_n^2}.$

---

In [3]:
np.linalg.norm(a)

3.7416573867739413

---

Cauchy-Schwarz inequality $-1\leq\frac{a\cdot b}{\lVert a\rVert\lVert b\rVert}\leq1.$

---

In [4]:
np.dot(a, b) / (np.linalg.norm(a)*np.linalg.norm(b))

0.9746318461970762

---

Matrix-vector product is simply a sequence of dot products of the rows of matrix (seen as vectors) with the vector

---

In [19]:
A = np.array([[1,2,-1,-1], [2,4,-2,3], [-1,1,-2,4]])
x = np.array([-1, 1, 1, 0])
print(A)
print(A.shape)
print(A[0])
print(A[1])
print(A[2])
print(A[0].shape)
print(x)
print(np.dot(A, x))

[[ 1  2 -1 -1]
 [ 2  4 -2  3]
 [-1  1 -2  4]]
(3, 4)
[ 1  2 -1 -1]
[ 2  4 -2  3]
[-1  1 -2  4]
(4,)
[-1  1  1  0]
[0 0 0]


---

A tensor of dimension 3 corresponding to 4 time stamps, 3 samples, 2 features (HR and BP)

---

In [6]:
# Create a tensor of dimesion 3
# 4 time stamps, 3 paitent, 2 features
T = np.array([[[74, 128], [79, 116], [71, 116]],
              [[78, 118], [82, 124], [72, 128]],
              [[84, 138], [84, 130], [74, 120]],
              [[82, 126], [76, 156], [82, 132]]])
print(T.shape)
print(T)
print(T[0])
print(T[0][0])

(4, 3, 2)
[[[ 74 128]
  [ 79 116]
  [ 71 116]]

 [[ 78 118]
  [ 82 124]
  [ 72 128]]

 [[ 84 138]
  [ 84 130]
  [ 74 120]]

 [[ 82 126]
  [ 76 156]
  [ 82 132]]]
[[ 74 128]
 [ 79 116]
 [ 71 116]]
[ 74 128]


---

Reshape tensor to represent (patient, feature, timestamps). That is, the timestamp becomes the last index.

---

In [15]:
T_reshaped = T.transpose(1, 2, 0)
print(T_reshaped)
print(T_reshaped[0])
print(T_reshaped[:, :, 1])

[[[ 74  78  84  82]
  [128 118 138 126]]

 [[ 79  82  84  76]
  [116 124 130 156]]

 [[ 71  72  74  82]
  [116 128 120 132]]]
[[ 74  78  84  82]
 [128 118 138 126]]
[[ 78 118]
 [ 82 124]
 [ 72 128]]


In [17]:
T_reshaped = T.transpose(2,0,1)
print(T_reshaped)
print(T_reshaped[0])
print(T_reshaped[:, 2, :])

[[[ 74  79  71]
  [ 78  82  72]
  [ 84  84  74]
  [ 82  76  82]]

 [[128 116 116]
  [118 124 128]
  [138 130 120]
  [126 156 132]]]
[[74 79 71]
 [78 82 72]
 [84 84 74]
 [82 76 82]]
[[ 84  84  74]
 [138 130 120]]


In [18]:
T_reshaped=T.transpose(1,0,2)
print(T_reshaped)
print(T_reshaped[0])
print(T_reshaped[:, :, 1])

[[[ 74 128]
  [ 78 118]
  [ 84 138]
  [ 82 126]]

 [[ 79 116]
  [ 82 124]
  [ 84 130]
  [ 76 156]]

 [[ 71 116]
  [ 72 128]
  [ 74 120]
  [ 82 132]]]
[[ 74 128]
 [ 78 118]
 [ 84 138]
 [ 82 126]]
[[128 118 138 126]
 [116 124 130 156]
 [116 128 120 132]]


---

Tensor-vector product is simply a sequence of matrix-vector products which in turn are a sequence of dot products of vectors

---

In [9]:
x = np.array([1, 0])
print(T)
print(x)
print(T.shape)
print(x.shape)
print(np.dot(T, x))

[[[ 74 128]
  [ 79 116]
  [ 71 116]]

 [[ 78 118]
  [ 82 124]
  [ 72 128]]

 [[ 84 138]
  [ 84 130]
  [ 74 120]]

 [[ 82 126]
  [ 76 156]
  [ 82 132]]]
[1 0]
(4, 3, 2)
(2,)
[[74 79 71]
 [78 82 72]
 [84 84 74]
 [82 76 82]]


---

Linear combination of columns of the matrix using the components of the vector is equivalent to the dot product of the rows of the matrix with the vector

----

In [20]:
print(A)
print(x)
# Dot product of rows of A with x
print(np.dot(A, x))
# Linear combination of columns of A using components of x
print(x[0]*A[:, 0] + x[1]*A[:, 1] + x[2]*A[:, 2] + x[3]*A[:, 3])
np.sum(x[range(4)] * A[:, range(4)], axis = 1) # faster

[[ 1  2 -1 -1]
 [ 2  4 -2  3]
 [-1  1 -2  4]]
[-1  1  1  0]
[0 0 0]
[0 0 0]


array([0, 0, 0])

Matrix-Matrix product

In [22]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,10],[8,11],[9,12]])
print(A)
print(B)
print(np.dot(A, B))

[[1 2 3]
 [4 5 6]]
[[ 7 10]
 [ 8 11]
 [ 9 12]]
[[ 50  68]
 [122 167]]


Tensor-matrix

In [27]:
T = np.array([[[74, 128], [79, 116], [71, 116]],
              [[78, 118], [82, 124], [72, 128]],
              [[84, 138], [84, 130], [74, 120]],
              [[82, 126], [76, 156], [82, 132]]])
X=np.array([[0,1],[1,1]])
print(T.shape)
print(X.shape)
np.dot(T,X)

(4, 3, 2)
(2, 2)


array([[[128, 202],
        [116, 195],
        [116, 187]],

       [[118, 196],
        [124, 206],
        [128, 200]],

       [[138, 222],
        [130, 214],
        [120, 194]],

       [[126, 208],
        [156, 232],
        [132, 214]]])



---


The $\texttt{sympy}$ library in Python is for symbolic computing. When using this library, everything including numbers are treated as symbols. This library can be used for calculating the RREF of an augmented matrix coming from a system of linear equations. Consider the system of linear equations $$\boxed{\begin{align*}x_1+2x_2-x_3-x_4&={\color{cyan}1},\\2x_1+4x_2-2x_3+3x_4&={\color{cyan}3},\\-x_1+x_2-2x_3+4x_4&={\color{cyan}2}.\end{align*}}$$
Note the folowing equivalent ways of interpreting this system of equations:
$$\boxed{\begin{align*}\underbrace{\begin{bmatrix}
1 &2 & -1 & -1  \\
2 & 4 & -2 & 3  \\
-1 & 1 & -2 & 4   
\end{bmatrix}}_{A}\underbrace{\begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix}}_{x}&=\underbrace{\begin{bmatrix}{\color{cyan}1}\\{\color{cyan}3}\\{\color{cyan}2}\end{bmatrix}}_{\color{cyan}b}\end{align*}}\Longleftrightarrow \underbrace{\boxed{x_1a_1+x_2a_2+x_3a_3+x_4a_4 = {\color{cyan}b}}}_{\color{green}{\text{linear combination of columns of }A}}\Longleftrightarrow \underbrace{\boxed{\begin{bmatrix}a^{(1)}\cdot x\\a^{(2)}\cdot x\\a^{(3)}\cdot x\end{bmatrix} =\begin{bmatrix}{\color{cyan}1}\\{\color{cyan}3}\\{\color{cyan}2}\end{bmatrix}}.}_{\color{green}{\text{Dot product of }x\text{ with rows of }A}}$$ The augmented matrix for this system of equations is $$\begin{align*}
\begin{bmatrix}
1 &2 & -1 & -1 &\lvert& {\color{cyan}1}\\
2 & 4 & -2 & 3 & \lvert&{\color{cyan}3}\\
-1 & 1 & -2 & 4 & \lvert&{\color{cyan}2}
\end{bmatrix}.
\end{align*}$$
The RREF of this augmented matrix can be calculated using the following Python code:

---

In [ ]:
# Augmented matrix
Ag = sp.Matrix([[1,2,-1,-1,0], [2,4,-2,3,0], [-1,1,-2,4,0]])

# Return the RREF and the pivot column indices as a tuple
print(Ag.rref())

---

This shows that $x_1, x_2,$ and $x_4$ are pivot variables and that $x_3$ is the only free variable. This system is $\color{green}{consistent}$ with $\color{green}{infinitely\ many\ solutions}$ as we see from the RREF above that
$$x_1=-x_3-(2/5),\,x_2=x_3+(4/5),\,x_4=1/5,$$
where $x_3$ can be any (real) number. We can also express the solution in vector notation as follows:
\begin{align*}
x &= \begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix} = \begin{bmatrix}-x_3-\frac{2}{5}\\x_3+\frac{4}{5}\\x_3\\\frac{1}{5}\end{bmatrix} = \underbrace{x_3\begin{bmatrix}-1\\1\\1\\0\end{bmatrix}}_{\text{solution to }Ax=0}+\underbrace{\begin{bmatrix}-\frac{2}{5}\\\frac{4}{5}\\0\\\frac{1}{5}\end{bmatrix}}_{\text{particular solution}},
\end{align*}  
noting again that $x_3$ can be any (real) number. Note that the solution has two parts:

* the first one involving the free variable(s) is the solutions to $Ax = 0$ (called the null space solution);
* the next one is the particular solution to $Ax=b.$




---